---
title: "Map Tuition Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
```

```{r}
tuition_fn <- "data/tuition.shp"
schools_fn <- "data/schools.shp"
```

```{r}
tuition <- tuition_fn %>% read_sf()
schools <- schools_fn %>% read_sf()
```

```{r}
combined <- 
  schools %>% 
  transmute(name = schl_nm, geometry) %>% 
  mutate(type = "school") %>% 
  rbind(
    tuition %>% 
      select(name, geometry) %>% 
      mutate(type = "tuition")
  )
```


```{r}
total_num_colours <- 
  tuition %>% 
  st_drop_geometry() %>%
  distinct(curriculum) %>% 
  nrow()
```


```{r}
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircles(
    color = ~ colorFactor(scales::hue_pal()(2), domain = combined$type)(type),
    weight = 3,
    label = ~ name,
    data = combined
  )
```


```{r}
# leaflet() %>% 
#   addProviderTiles(providers$CartoDB.Positron) %>% 
#   addCircles(
#     color = ~ colorFactor(scales::hue_pal()(total_num_colours), domain = tuition$curriculum)(curriculum),
#     weight = 3,
#     label = ~ str_c(name, " (", curriculum, ")"),
#     data = tuition
#   )
```

